Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ASPNPlatzi.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNPlatzi.Controllers
{
    public class AlumnoController : Controller
    {
        public IActionResult index()
        {
            ViewBag.Information = "Se yon boon elèv";
            ViewBag.Fecha = DateTime.Now;
            return View(new Alumno{Nombre = "Joe Watson SBF", UniqueId = Guid.NewGuid().ToString()});
        }
        public IActionResult MultiAlumno()
        {
            var asignatura = new Asignatura();
            asignatura.Nombre = "Programacion Orientado a Objeto";
            asignatura.UniqueId = Guid.NewGuid().ToString();

            var listaAlumnos = GenerarAlumnosAlAzar();

            ViewBag.Information = "Se yon boon elèv";
            ViewBag.Fecha = DateTime.Now;
            
            return View("MultiAlumno",listaAlumnos);
        }

        private List<Alumno> GenerarAlumnosAlAzar()
        {
            string[] nombre1 = { "Alba", "Felipa", "Eusebio", "Farid", "Donald", "Alvaro", "Nicolás" };
            string[] apellido1 = { "Ruiz", "Sarmiento", "Uribe", "Maduro", "Trump", "Toledo", "Herrera" };
            string[] nombre2 = { "Freddy", "Anabel", "Rick", "Murty", "Silvana", "Diomedes", "Nicomedes", "Teodoro" };

            var listaAlumnos = from n1 in nombre1
                               from n2 in nombre2
                               from a1 in apellido1
                               select new Alumno { Nombre = $"{n1} {n2} {a1}", UniqueId = Guid.NewGuid().ToString() };

            return listaAlumnos.OrderBy((al) => al.UniqueId).ToList();
        }
    }
}

Controllers/AsignaturaController.cs
using System;
using System.Collections.Generic;
using ASPNPlatzi.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNPlatzi.Controllers
{
    public class AsignaturaController : Controller
    {
        public IActionResult index()
        {
            ViewBag.Information = "Klas sa enpòtan anpil pou devlòpman WEB";
            ViewBag.Fecha = DateTime.Now;
            return View(new Asignatura{Nombre = "Programacion Orientado a Objeto", UniqueId = Guid.NewGuid().ToString()});
        }
        public IActionResult MultiAsignatura()
        {
            var asignatura = new Asignatura();
            asignatura.Nombre = "Programacion Orientado a Objeto";
            asignatura.UniqueId = Guid.NewGuid().ToString();

            var listaAsignaturas = new List<Asignatura>(){
                new Asignatura{Nombre = "Programacion Orientado a Objeto", UniqueId = Guid.NewGuid().ToString()},
                new Asignatura{Nombre="Matemáticas", UniqueId = Guid.NewGuid().ToString()} ,
                new Asignatura{Nombre="Educación Física", UniqueId = Guid.NewGuid().ToString()},
                new Asignatura{Nombre="Castellano", UniqueId = Guid.NewGuid().ToString()},
                new Asignatura{Nombre="Ciencias Naturales", UniqueId = Guid.NewGuid().ToString()}
            };

            ViewBag.Information = "Klas sa enpòtan anpil pou devlòpman WEB";
            ViewBag.Fecha = DateTime.Now;
            
            return View("MultiAsignatura",listaAsignaturas);
        }
    }
}

Controllers/EscuelaController.cs
using System;
using ASPNPlatzi.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNPlatzi.Controllers
{
    public class EscuelaController : Controller
    {
        public IActionResult Index()
        {
            var escuela = new Escuela() ;
            escuela.AnoDeCreacion=2019;
            escuela.UniqueId = Guid.NewGuid().ToString();
            escuela.Nombre = "Program et Action";
            escuela.Ciudad = "Cap Haitien";
            escuela.Pais = "Haiti";
            escuela.Dirección = "Rue 18 K";
            escuela.TipoEscuela = TiposEscuela.Secundaria;

            ViewBag.Information = "Tout kou nou yo fèt an KREYÒL AYISYEN!";
            
            return View(escuela);
        }
    }
}

Views/Shared/AsignaturaSimple.cshtml
@Model Asignatura


<tbody>
    <tr>
        <th>@Model.UniqueId</th>
        <td>@Model.Nombre</td>
        <td>@ViewBag.Information</td>
        <td>@ViewBag.Fecha</td>
    </tr>
</tbody>

Views/Shared/ListaObjetoEscuela.cshtml
@*
Model List<ObjetoEscuelaBase>
*@


<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Información</th>
            <th scope="col">Fecha</th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var obj in Model)
        {
            <tr>
                
                @* <partial name = "ObjetoEscuelaSimple"  model="obj" />  *@
                
                <th>@obj.UniqueId</th>
                <td>@obj.Nombre</td>
                <td>@ViewBag.Information</td>
                <td>@ViewBag.Fecha</td>
                </tr>
        }
       
    </tbody>
</table>

Views/Shared/ObjetoEscuelaSimple.cshtml
@*
@Model ObjetoEscuelaBase

<tbody>
    <tr>
        <th>@Model.UniqueId</th>
        <td>@Model.Nombre</td>
        <td>@ViewBag.Information</td>
        <td>@ViewBag.Fecha</td>
    </tr>
</tbody>
*@

Views/Shared/Simple.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
    crossorigin="anonymous">

</head>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Program et Action</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escuela" asp-action="Index">Escuela</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura" asp-action="Index">Asignatura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="Index">Alumno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" 
    crossorigin="anonymous"></script>
    
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PA</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
    crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Program et Action</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escuela" asp-action="Index">Escuela</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Program et Action - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" 
    crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>